apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchers-deploy
  labels:
    app: watchers-app
  annotations:
spec:
  selector:
    matchLabels:
      app: watchers-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: watchers-app
    spec:
      containers:
      - name: cosmoshub-4
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://23.90.70.41:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: bostromdev-1
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://167.172.103.118:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: regen-devnet-5
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://18.220.101.192:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: musselnet-3
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://188.34.187.55:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: musselnet-4
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://157.90.153.184:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: akashnet-2
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://135.181.60.250:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: akash-testnet-5
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://147.75.32.11:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: irishub-1
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://66.42.116.195:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: nyancat-7
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:fb0b0363
        env:
          - name: rpc
            value: "http://34.80.202.172:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      # - name: tanute-1
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.173:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: xasonk-3
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.174:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: erieri
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.175:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: lalbri-1
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.176:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: fadeld
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.177:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: fontor-1
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.178:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: yacafi-6
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.179:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: chelll
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.180:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: hobhin-1
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.181:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: ftandy-2
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.182:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: eyarss-1
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.183:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: wnncku
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.184:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"

      # - name: brenav-1
      #   image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:efak95b0
      #   env:
      #     - name: rpc
      #       value: "http://34.80.202.185:26657"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: hackatomsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "1Mi"
      #       cpu: "1m"
      #     limits:
      #       memory: "1Mi"
      #       cpu: "1m"
