apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchers-deploy
  labels:
    app: watchers-app
  annotations:
spec:
  selector:
    matchLabels:
      app: watchers-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: watchers-app
    spec:
      containers:
      - name: cosmoshub-4
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:172f69b6
        env:
          - name: rpc
            value: "http://23.90.70.41:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: bostromdev-1
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:1aa18a09
        env:
          - name: rpc
            value: "http://167.172.103.118:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: regen-devnet-5
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:1aa18a09
        env:
          - name: rpc
            value: "http://18.220.101.192:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: musselnet-3
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:1aa18a09
        env:
          - name: rpc
            value: "http://188.34.187.55:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: musselnet-4
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:1aa18a09
        env:
          - name: rpc
            value: "http://157.90.153.184:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: akashnet-2
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:c93fa940
        env:
          - name: rpc
            value: "http://135.181.60.250:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      - name: akash-testnet-5
        image: registry.digitalocean.com/mapofzones/hackatom-cosmos-watcher:c93fa940
        env:
          - name: rpc
            value: "http://147.75.32.11:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: hackatomsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"
