apiVersion: argoproj.io/v1alpha1
metadata:
  name: hackatom-starway
  namespace: argocd
spec:
  destination:
    namespace: hackatom
    server: 'https://kubernetes.default.svc'
  source:
    path: hackatom
    repoURL: 'https://github.com/starway-monster/deploy.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
kind: Application